import Head from 'next/head';
import Header from './organisms/Header';
import styles from '../styles/Home.module.scss';

interface MainContainerProps {
	//TODO
	children: any;
	title: string;
}

const MainContainer = ({ children, title }: MainContainerProps) => {
	return (
		<div className={styles.wrapper}>
			<Head>
				<title>{title}</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<div className={styles.container}>{children}</div>
		</div>
	);
};

export default MainContainer;
